# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1
minecraft_major_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.1.2-beta
moddevgradle_version=2.0.141

parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20

## Mod Properties

mod_id=theurgy
mod_group_id=com.klikli_dev
mod_name=Theurgy
mod_license=MIT AND CC-BY-4.0
mod_version=1.80.0
mod_authors=Kli Kli
mod_description=An open-source magic mod built around classical alchemy to replicate and transmute matter, and create magical artifacts.

## Dependency Properties

jei_version=29.2.0.21
modonomicon_version=1.130.0
occultism_version=1.209.0
almost_unified_version=0.5.0
geckolib_version=5.5
jade_version=26.0.6
emi_version=1.1.12
