# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.2
minecraft_major_version=26.2
minecraft_version_range=[26.2,26.3)
neo_version=26.2.0.8-beta
moddevgradle_version=2.0.142

## Mod Properties

mod_id=theurgy
mod_group_id=com.klikli_dev
mod_name=Theurgy
mod_license=MIT AND CC-BY-4.0
mod_version=1.114.0
mod_authors=Kli Kli
mod_description=An open-source magic mod built around classical alchemy to replicate and transmute matter, and create magical artifacts.

## Dependency Properties

jei_version=30.15.0.113
modonomicon_version=2.2.0
code_defined_gui_version=1.12.0
magic_particles_lib_version=1.4.0
occultism_version=1.234.0
almost_unified_version=0.5.0
geckolib_version=5.5.3
jade_version=26.2.8
emi_version=1.1.12
