// SPDX-FileCopyrightText: 2023 klikli-dev
//
// SPDX-License-Identifier: MIT

package com.klikli_dev.theurgy.content.recipe;

import com.klikli_dev.theurgy.content.recipe.display.CatalysationRecipeDisplay;
import com.klikli_dev.theurgy.content.recipe.input.ItemHandlerRecipeInput;
import com.klikli_dev.theurgy.registry.BlockRegistry;
import com.klikli_dev.theurgy.registry.RecipeSerializerRegistry;
import com.klikli_dev.theurgy.registry.RecipeTypeRegistry;
import com.mojang.serialization.Codec;
import com.mojang.serialization.MapCodec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.NonNullList;
import net.minecraft.network.RegistryFriendlyByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.*;
import net.minecraft.world.item.crafting.display.RecipeDisplay;
import net.minecraft.world.item.crafting.display.SlotDisplay;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.NotNull;

import java.util.List;


/**
 * @param mercuryFluxPerTick The amount of mercury flux to generate per tick, until the total amount has been reached
 * @param totalMercuryFlux   The total amount of mercury flux generated by consuming the ingredient.
 */
public record CatalysationRecipe(Ingredient ingredient, int totalMercuryFlux,
                                 int mercuryFluxPerTick) implements Recipe<ItemHandlerRecipeInput> {
    public static final int DEFAULT_MERCURY_FLUX_PER_TICK = 20;

    public static final MapCodec<CatalysationRecipe> CODEC = RecordCodecBuilder.mapCodec(instance -> instance.group(
                    Ingredient.CODEC.fieldOf("ingredient").forGetter(r -> r.ingredient),
                    Codec.INT.fieldOf("totalMercuryFlux").forGetter(r -> r.totalMercuryFlux),
                    Codec.INT.fieldOf("mercuryFluxPerTick").forGetter(r -> r.mercuryFluxPerTick)
            ).apply(instance, CatalysationRecipe::new)
    );

    public static final StreamCodec<RegistryFriendlyByteBuf, CatalysationRecipe> STREAM_CODEC = StreamCodec.composite(
            Ingredient.CONTENTS_STREAM_CODEC,
            r -> r.ingredient,
            ByteBufCodecs.INT,
            r -> r.totalMercuryFlux,
            ByteBufCodecs.INT,
            r -> r.mercuryFluxPerTick,
            CatalysationRecipe::new
    );
    public static final RecipeSerializer<CatalysationRecipe> SERIALIZER = new RecipeSerializer<>(CODEC, STREAM_CODEC);

    @Override
    public @NotNull RecipeType<CatalysationRecipe> getType() {
        return RecipeTypeRegistry.CATALYSATION.get();
    }

    @Override
    public boolean matches(@NotNull ItemHandlerRecipeInput pContainer, @NotNull Level pLevel) {
        var stack = pContainer.getItem(0);
        return this.ingredient.test(stack);
    }

    @Override
    public ItemStack assemble(ItemHandlerRecipeInput pCraftingContainer) {
        return ItemStack.EMPTY;
    }

    @Override
    public boolean showNotification() {
        return true;
    }

    @Override
    public String group() {
        return "";
    }

//    @Override
//    public boolean canCraftInDimensions(int pWidth, int pHeight) {
//        return true;
//    }

    public ItemStack getResultItem(HolderLookup.Provider pRegistries) {
        return ItemStack.EMPTY;
    }

    @Override
    public RecipeBookCategory recipeBookCategory() {
        return RecipeBookCategories.CRAFTING_MISC;
    }

    @Override
    public PlacementInfo placementInfo() {
        return PlacementInfo.NOT_PLACEABLE;
    }

    public @NotNull NonNullList<Ingredient> getIngredients() {
        NonNullList<Ingredient> list = NonNullList.create();
        list.add(this.ingredient);
        return list;
    }

    @Override
    public @NotNull RecipeSerializer<CatalysationRecipe> getSerializer() {
        return RecipeSerializerRegistry.CATALYSATION.get();
    }

    @Override
    public List<RecipeDisplay> display() {
        return List.of(new CatalysationRecipeDisplay(
                this.ingredient,
                this.totalMercuryFlux,
                this.mercuryFluxPerTick,
                new SlotDisplay.ItemSlotDisplay(BlockRegistry.MERCURY_CATALYST.get().asItem())
        ));
    }

}
